### ISSUE TITLE
Data Container

### ISSUE THREAD

**Issue by YagmurSimsekk** [microbiome/miaSim#52]
Currently, none of the simulation functions output TSE or SE, they are either matrix or list objects. If that's not going to change, I suggest deleting "The package is part of miaverse, and is based on the (Tree)SummarizedExperiment data container." in README section. 

Also, should we still keep [convertToSE](https://github.com/microbiome/miaSim/blob/main/R/convertToSE.R) function? I don't see a reason to keep it. 

I can make the mentioned changes once it is confirmed by others.

**Comment by gaoyu19920914** [comment]
It is okay for me to drop that phrase in README and remove the convertToSE function.

**Comment by antagomir** [comment]
I will have a closer look next week but could we reiterate the reasoning for not supporting the TreeSE objects?

It could be beneficial to support a standard data container, and all the necessary data elements are very easy to take out when needed, in particular:

- Abundance tabel: `x <- assay(tse, "counts")`
- Sample metadata: `df <- colData(tse)`

If the package is not supporting TreeSE, then the package name should be changed from _miaSim_ to something else because it is not part of the collection any more. We could potentially add wrappers on top of this to other independent packages in such case.

**Comment by antagomir** [comment]
Can we here go through the arguments for the different options, I guess the output options now is to provide 1) matrices; or 2) TreeSE objects. @gaoyu19920914 do you have a clear preference?

**Comment by antagomir** [comment]
Done in the ongoing PRs.
